stages:
  - build
  - deploy
  - .post

variables:
  CHANNEL: "production"

  DOCKER_REGISTRY_PASSWORD: "${DOCKER_REGISTRY_PASSWORD}"
  DOCKER_REGISTRY_LOGIN: "${DOCKER_REGISTRY_LOGIN}"
  DOCKER_REGISTRY_HOSTNAME: "${DOCKER_REGISTRY_HOSTNAME}"

  DOCKER_IMAGE_PREFIX: "${DOCKER_REGISTRY_HOSTNAME}/${PROJECT_ID}/${SUBPROJECT_ID}/${SERVICE}"

  CRESCO_DB_MONGO_CONNECTION_STRING: "${CRESCO_DB_MONGO_CONNECTION_STRING}"
  CRESCO_STORAGE_S3_BUCKET_ENDPOINT: "${CRESCO_STORAGE_S3_BUCKET_ENDPOINT}"
  CRESCO_STORAGE_S3_BUCKET_NAME: "${CRESCO_STORAGE_S3_BUCKET_NAME}"
  CRESCO_STORAGE_S3_BUCKET_ACCESS_KEY_ID: "${CRESCO_STORAGE_S3_BUCKET_ACCESS_KEY_ID}"
  CRESCO_STORAGE_S3_BUCKET_SECRET_KEY: "${CRESCO_STORAGE_S3_BUCKET_SECRET_KEY}"
  CRESCO_JWT_SECRET_KEY: "${CRESCO_JWT_SECRET_KEY}"
  CRESCO_SENDER_SMTP_PASSWORD: "${CRESCO_SENDER_SMTP_PASSWORD}"
  CRESCO_HUOBI_KEY: "${CRESCO_HUOBI_KEY}"
  CRESCO_HUOBI_SECRET_KEY: "${CRESCO_HUOBI_SECRET_KEY}"


include:
  - local: '/.gitlab-ci/build-backend-production.gitlab-ci.yml'
  - local: '/.gitlab-ci/build-frontend-production.gitlab-ci.yml'
  - local: '/.gitlab-ci/deploy-production.gitlab-ci.yml'
