---
version: "3.8"

services:
  backend:
    image: "dr.metafora.dev/cresco/monorepo/backend/none:latest"
    pull_policy: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cresco-monorepo-backend-metafora.rule=Host(`backend.cresco.production.metafora.dev`)||(Host(`cresco.production.metafora.dev`)&&(PathPrefix(`/graphql`)||PathPrefix(`/api`)))"
      - "traefik.http.routers.cresco-monorepo-backend-domain.rule=Host(`cabinet.cresco.capital`)&&(PathPrefix(`/graphql`)||PathPrefix(`/api`)))"
      - "traefik.http.services.cresco-monorepo-backend.loadbalancer.server.port=3000"
      - "traefik.http.routers.cresco-monorepo-backend.entrypoints=web"
      - "traefik.http.routers.cresco-monorepo-backend-metafora.service=cresco-monorepo-backend"
      - "traefik.http.routers.cresco-monorepo-backend-domain.service=cresco-monorepo-backend"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          memory: 512M
          cpus: '0.50'
        reservations:
          cpus: '0.25'
          memory: 256M
      labels:
        - "traefik.enable=true"

        - "traefik.http.routers.cresco-monorepo-backend.rule=Host(`backend.cresco.production.metafora.dev`)||(Host(`cresco.production.metafora.dev`)&&(PathPrefix(`/graphql`)||PathPrefix(`/api`)))"
        - "traefik.http.services.cresco-monorepo-backend.loadbalancer.server.port=3000"
        - "traefik.http.routers.cresco-monorepo-backend-metafora.entrypoints=web"
        - "traefik.http.routers.cresco-monorepo-backend-domain.entrypoints=web"
        - "traefik.http.routers.cresco-monorepo-backend-metafora.service=cresco-monorepo-backend"
        - "traefik.http.routers.cresco-monorepo-backend-domain.service=cresco-monorepo-backend"
    environment:
      - "CRESCO_DB_MONGO_CONNECTION_STRING=${CRESCO_DB_MONGO_CONNECTION_STRING}"
      - "CRESCO_STORAGE_S3_BUCKET_ENDPOINT=${CRESCO_STORAGE_S3_BUCKET_ENDPOINT}"
      - "CRESCO_STORAGE_S3_BUCKET_NAME=${CRESCO_STORAGE_S3_BUCKET_NAME}"
      - "CRESCO_STORAGE_S3_BUCKET_ACCESS_KEY_ID=${CRESCO_STORAGE_S3_BUCKET_ACCESS_KEY_ID}"
      - "CRESCO_STORAGE_S3_BUCKET_SECRET_KEY=${CRESCO_STORAGE_S3_BUCKET_SECRET_KEY}"
      - "CRESCO_JWT_SECRET_KEY=${CRESCO_JWT_SECRET_KEY}"
      - "CRESCO_SENDER_SMTP_PASSWORD=${CRESCO_SENDER_SMTP_PASSWORD}"
      - "CRESCO_HUOBI_KEY=${CRESCO_HUOBI_KEY}"
      - "CRESCO_HUOBI_SECRET_KEY=${CRESCO_HUOBI_SECRET_KEY}"
    networks:
      cresco:
        aliases:
          - cresco-monorepo-backend
      cresco-monorepo:
        aliases:
          - cresco-monorepo-backend
      cresco_ext:
        aliases:
          - cresco-monorepo-backend

  frontend:
    image: "dr.metafora.dev/cresco/monorepo/frontend/none:latest"
    pull_policy: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cresco-monorepo-frontend-metafora.rule=Host(`cresco.production.metafora.dev`)||Host(`frontend.cresco.production.metafora.dev`)"
      - "traefik.http.routers.cresco-monorepo-frontend-domain.rule=Host(`cabinet.cresco.capital`)"
      - "traefik.http.services.cresco-monorepo-frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.cresco-monorepo-frontend-metafora.entrypoints=web"
      - "traefik.http.routers.cresco-monorepo-frontend-domain.entrypoints=web"
      - "traefik.http.routers.cresco-monorepo-frontend-metafora.service=cresco-monorepo-frontend"
      - "traefik.http.routers.cresco-monorepo-frontend-domain.service=cresco-monorepo-frontend"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          memory: 512M
          cpus: '0.50'
        reservations:
          cpus: '0.25'
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.cresco-monorepo-frontend-metafora.rule=Host(`cresco.production.metafora.dev`)||Host(`frontend.cresco.production.metafora.dev`)"
        - "traefik.http.routers.cresco-monorepo-frontend-domain.rule=Host(`cabinet.cresco.capital`)"
        - "traefik.http.services.cresco-monorepo-frontend.loadbalancer.server.port=3000"
        - "traefik.http.routers.cresco-monorepo-frontend.entrypoints=web"
        - "traefik.http.routers.cresco-monorepo-frontend.service=cresco-monorepo-frontend"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    environment:
      - "BACKAEND_URI=http://cresco-monorepo-backend:3000"
    networks:
      cresco:
        aliases:
          - cresco-monorepo-frontend
      cresco-monorepo:
        aliases:
          - cresco-monorepo-frontend
      cresco_ext:
        aliases:
          - cresco-monorepo-frontend

  queue:
    image: "redis:latest"
    pull_policy: always
    labels:
      # - "traefik.enable=true"
      - "traefik.http.services.cresco-monorepo-queue.loadbalancer.server.port=6379"
      - "traefik.http.routers.cresco-monorepo-queue.service=cresco-monorepo-queue"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          memory: 512M
          cpus: '0.50'
        reservations:
          cpus: '0.25'
          memory: 256M
      labels:
        # - "traefik.enable=true"
        - "traefik.http.services.cresco-monorepo-queue.loadbalancer.server.port=6379"
        - "traefik.http.routers.cresco-monorepo-queue.service=cresco-monorepo-queue"
    networks:
      cresco:
        aliases:
          - cresco-monorepo-queue
      cresco-monorepo:
        aliases:
          - cresco-monorepo-queue
networks:

  cresco:
    external: true
    name: cresco

  cresco-monorepo:
    external: true
    name: cresco-monorepo

  cresco_ext:
    external: true
    name: cresco_ext
...
