---
version: "3.8"

services:
  backend:
    image: "dr.metafora.dev/cresco/monorepo/backend/production:latest"
    labels:
      - "traefik.http.routers.cresco-monorepo-backend-metafora.rule=(Host(`cresco.production.metafora.dev`)||Host(`www.cresco.production.metafora.dev`))&&(PathPrefix(`/graphql`)||PathPrefix(`/api`))"
      - "traefik.http.routers.cresco-monorepo-backend-metafora.entrypoints=web,websecure"
      - "traefik.http.routers.cresco-monorepo-backend-metafora.tls.certresolver=http-cert"
      - "traefik.http.routers.cresco-monorepo-backend-metafora.tls.domains[0].main=cresco.production.metafora.dev"
      - "traefik.http.routers.cresco-monorepo-backend-metafora.tls.domains[0].sans=backend.cresco.production.metafora.dev"
      - "traefik.http.routers.cresco-monorepo-backend-metafora.tls=true"

      - "traefik.http.routers.cresco-monorepo-backend-domain.rule=(Host(`cabinet.cresco.capital`)||Host(`www.cabinet.cresco.capital`))&&(PathPrefix(`/graphql`)||PathPrefix(`/api`))"
      - "traefik.http.routers.cresco-monorepo-backend-domain.entrypoints=web,websecure"
      - "traefik.http.routers.cresco-monorepo-backend-domain.tls.certresolver=http-cert"
      - "traefik.http.routers.cresco-monorepo-backend-domain.tls.domains[0].main=cabinet.cresco.capital"
      - "traefik.http.routers.cresco-monorepo-backend-domain.tls.domains[0].sans=www.cabinet.cresco.capital"
      - "traefik.http.routers.cresco-monorepo-backend-domain.tls=true"
    environment:
      - "CRESCO_DB_MONGO_CONNECTION_STRING=${CRESCO_DB_MONGO_CONNECTION_STRING}"
      - "CRESCO_STORAGE_S3_BUCKET_ENDPOINT=${CRESCO_STORAGE_S3_BUCKET_ENDPOINT}"
      - "CRESCO_STORAGE_S3_BUCKET_NAME=${CRESCO_STORAGE_S3_BUCKET_NAME}"
      - "CRESCO_STORAGE_S3_BUCKET_ACCESS_KEY_ID=${CRESCO_STORAGE_S3_BUCKET_ACCESS_KEY_ID}"
      - "CRESCO_STORAGE_S3_BUCKET_SECRET_KEY=${CRESCO_STORAGE_S3_BUCKET_SECRET_KEY}"
      - "CRESCO_JWT_SECRET_KEY=${CRESCO_JWT_SECRET_KEY}"
      - "CRESCO_SENDER_SMTP_PASSWORD=${CRESCO_SENDER_SMTP_PASSWORD}"
      - "CRESCO_HUOBI_KEY=${CRESCO_HUOBI_KEY}"
      - "CRESCO_HUOBI_SECRET_KEY=${CRESCO_HUOBI_SECRET_KEY}"
    deploy:
      labels:
        - "traefik.http.routers.cresco-monorepo-backend-metafora.rule=(Host(`cresco.production.metafora.dev`)||Host(`www.cresco.production.metafora.dev`))&&(PathPrefix(`/graphql`)||PathPrefix(`/api`))"
        - "traefik.http.routers.cresco-monorepo-backend-metafora.entrypoints=web,websecure"
        - "traefik.http.routers.cresco-monorepo-backend-metafora.tls.certresolver=http-cert"
        - "traefik.http.routers.cresco-monorepo-backend-metafora.tls.domains[0].main=cresco.production.metafora.dev"
        - "traefik.http.routers.cresco-monorepo-backend-metafora.tls.domains[0].sans=www.cresco.production.metafora.dev"
        - "traefik.http.routers.cresco-monorepo-backend-metafora.tls=true"

        - "traefik.http.routers.cresco-monorepo-backend-domain.rule=(Host(`cabinet.cresco.capital`)||Host(`www.cabinet.cresco.capital`))&&(PathPrefix(`/graphql`)||PathPrefix(`/api`))"
        - "traefik.http.routers.cresco-monorepo-backend-domain.entrypoints=web,websecure"
        - "traefik.http.routers.cresco-monorepo-backend-domain.tls.certresolver=http-cert"
        - "traefik.http.routers.cresco-monorepo-backend-domain.tls.domains[0].main=cabinet.cresco.capital"
        - "traefik.http.routers.cresco-monorepo-backend-domain.tls.domains[0].sans=www.cabinet.cresco.capital"
        - "traefik.http.routers.cresco-monorepo-backend-domain.tls=true"


  frontend:
    image: "dr.metafora.dev/cresco/monorepo/frontend/production:latest"
    labels:
      - "traefik.http.routers.cresco-monorepo-frontend-metafora.rule=Host(`cresco.production.metafora.dev`)||Host(`www.cresco.production.metafora.dev`)"
      - "traefik.http.routers.cresco-monorepo-frontend-metafora.entrypoints=web,websecure"
      - "traefik.http.routers.cresco-monorepo-frontend-metafora.tls.certresolver=http-cert"
      - "traefik.http.routers.cresco-monorepo-frontend-metafora.tls.domains[0].main=cresco.production.metafora.dev"
      - "traefik.http.routers.cresco-monorepo-frontend-metafora.tls.domains[0].sans=www.cresco.production.metafora.dev"
      - "traefik.http.routers.cresco-monorepo-frontend-metafora.tls=true"

      - "traefik.http.routers.cresco-monorepo-frontend-domain.rule=Host(`cabinet.cresco.capital`)||Host(`www.cabinet.cresco.capital`)"
      - "traefik.http.routers.cresco-monorepo-frontend-domain.entrypoints=web,websecure"
      - "traefik.http.routers.cresco-monorepo-frontend-domain.tls.certresolver=http-cert"
      - "traefik.http.routers.cresco-monorepo-frontend-domain.tls.domains[0].main=cabinet.cresco.capital"
      - "traefik.http.routers.cresco-monorepo-frontend-domain.tls.domains[0].sans=www.cabinet.cresco.capital"
      - "traefik.http.routers.cresco-monorepo-frontend-domain.tls=true"
    deploy:
      labels:
        - "traefik.http.routers.cresco-monorepo-frontend-metafora.rule=Host(`cresco.production.metafora.dev`)||Host(`www.cresco.production.metafora.dev`)"
        - "traefik.http.routers.cresco-monorepo-frontend-metafora.entrypoints=web,websecure"
        - "traefik.http.routers.cresco-monorepo-frontend-metafora.tls.certresolver=http-cert"
        - "traefik.http.routers.cresco-monorepo-frontend-metafora.tls.domains[0].main=cresco.production.metafora.dev"
        - "traefik.http.routers.cresco-monorepo-frontend-metafora.tls.domains[0].sans=www.cresco.production.metafora.dev"
        - "traefik.http.routers.cresco-monorepo-frontend-metafora.tls=true"

        - "traefik.http.routers.cresco-monorepo-frontend-domain.rule=Host(`cabinet.cresco.capital`)||Host(`www.cabinet.cresco.capital`)"
        - "traefik.http.routers.cresco-monorepo-frontend-domain.entrypoints=web,websecure"
        - "traefik.http.routers.cresco-monorepo-frontend-domain.tls.certresolver=http-cert"
        - "traefik.http.routers.cresco-monorepo-frontend-domain.tls.domains[0].main=cabinet.cresco.capital"
        - "traefik.http.routers.cresco-monorepo-frontend-domain.tls.domains[0].sans=www.cabinet.cresco.capital"
        - "traefik.http.routers.cresco-monorepo-frontend-domain.tls=true"
  queue:
    volumes:
      - type: bind
        source: /opt/cresco/backend/queue/data/
        target: /data
        read_only: false

...
